---
# SPDX-License-Identifier: LGPL-2.1-or-later
# vi: ts=2 sw=2 et:

name: Build & boot test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README*'
      - 'TODO'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README*'
      - 'TODO'

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ toJSON(matrix.distro) }}-${{ matrix.phase }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        distro:
          - {name: fedora, tag: rawhide }
        phase:
          - INITRD_BASIC
          - INITRD_LVM
          - INITRD_LUKS
          - INITRD_LUKS_LVM
            #- INITRD_ISCSI # iSCSI is missing a generator
          - SYSEXT
    container:
      image: "${{ matrix.distro.name }}:${{ matrix.distro.tag }}"
      options: --privileged
      # We need to have directories which mkosi uses for its overlayfs on a
      # "real" filesystem (not an overlayfs), since we can't nest read/write
      # layers. Also, it can't be tmpfs, since generating sysext images uses
      # user xattrs. And to correctly propagate loop devices/partitions
      # between the container and the host we need to explicitly mount host's
      # /dev into the container.
      volumes: ["/var/tmp:/var/tmp", "/dev:/dev"]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: ./.github/workflows/build-${{ matrix.distro.name }}.sh DEPS

      - name: ${{ matrix.phase }} on ${{ matrix.distro.name }}:${{ matrix.distro.tag }}
        run: ./.github/workflows/build-${{ matrix.distro.name }}.sh ${{ matrix.phase }}
